name: flutter_mdns_plugin
description: Flutter mDNS plugin
version: 1.0.0
author: Estia Software DMCC
homepage: https://estiasoftware.com/
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.estiasoftware.fluttermdnsplugin
    pluginClass: FlutterMdnsPlugin
